### ISSUE TITLE
differences-Aug-8-2019.xml - feedback

### ISSUE THREAD

**Issue by matmaxgeds** [kndm/iati-diff#10]
1. Where are the input files to use to check?
2. what is this: "http://namespaces.shoobx.com/diff"?
3. Remove: diff:delete=""
4. Rows 21 and 22 - unclear why row 22 exists
5. How do I see where whole elements have been added/removed?
6. Row 76 is a mistake?
7. Row 82 is a mistake?
8. Row 87 is a mistake?

**Comment by kndm** [comment]
1. The input files can now be found at input-test folder
2. This can be removed, it is just added by the library we're currently using and won't be an issue.
3. This is signaled as to what should be deleted from the right file to look like the left file (original). For example, line [3,4,5] and [6,7,8] of the output file, are actually just letting us know that lines [3,4,5] should be added, and line [6,7,8] should be deleted.
4. Not an error, if we look into the input files, we can see that line 22,23 should be added for it to look like the original file's, if any error is found here it could be on the inputs itself.
5. Anything that only has an insert not immediately followed by a delete is an actual new element, for example line 79 in the datastore file, it does not exist in the list file therefore it is added to the output in line 104.
6. It is, forgot to mention that this was ran with 0.9 out of 1 as F parameter (meaning that it has to be at least 90% similar to determine it as a difference) to check how close it would be as some errors were experienced with 1 but this was found to be mostly caused due to some formatting from when the xml inputs are generated and I have fixed it, I will put now a different output file with a F = 1 value to compare results.
7. Same as 6
8. Same as 6

**Comment by matmaxgeds** [comment]
Closing and putting as individual issues
